# Default configuration file for ez_ufo_qt
# Modify at your own peril

---
e_indir: ""
e_tmpdir: ""
e_outdir: ""
e_darks: "darks"
e_flats: "flats"
e_tomo: "tomo"
e_flats2: "flats2"
e_bigtif: false
e_ax: 1
e_ax_range: "1010,1030,0.5"
e_ax_row: 100
e_ax_p_size: 256
e_ax_fix: 0.0
e_dax: 0.0
e_inp: false
e_inp_thr: 1000
e_inp_sig: 2
e_RR: false
e_RR_ufo: true
e_RR_ufo_1d: true
e_RR_sig_hor: 3
e_RR_sig_ver: 2
e_rr_srp_wind_sort: 21
e_rr_srp_wide: false
e_rr_srp_wind_wide: 91
e_rr_srp_snr: 3
e_PR: false
e_energy: 20
e_pixel: 3.6
e_z: 0.1
e_log10db: 200
e_vcrop: false
e_y: 100
e_yheight: 200
e_ystep: 20
e_gray256: false
e_bit: 8
e_hmin: 0.0
e_hmax: 0.0
e_pre: false
e_pre_cmd: "remove-outliers size=3 threshold=500 sign=1"
e_a0: 0.0
e_crop: false
e_x0: 0
e_dx: 0
e_y0: 0
e_dy: 0
e_dryrun: false
e_parfile: true
e_keep_tmp: false
e_sinFFC: false
e_sinFFC_method: 1
e_sinFFCEigenReps: 4
e_sinFFCEigenDowns: 2
e_sinFFCDowns: 4
e_openIV: True
e_common_darks_flats: False
e_common_darks: "Absolute path to darks"
e_common_flats: "Absolute path to flats"
e_use_common_flats2: False
e_common_flats2: "Absolute path to flats2"
#NLMDN Settings
e_nlmdn_apply_after_reco: False
e_nlmdn_indir: ""
e_nlmdn_input_is_file: False
e_nlmdn_outdir: ""
e_nlmdn_bigtif: False
e_nlmdn_r: 10
e_nlmdn_dx: 3
e_nlmdn_h: 0.0
e_nlmdn_sig: 0.0
e_nlmdn_w: 0.0
e_nlmdn_fast: True
e_nlmdn_autosig: False
e_nlmdn_dryrun: False
#ADVANCED TOFU Settings
e_adv_lamino_angle: 30
e_adv_overall_rotation: 360
e_adv_center_pos_z: ""
e_adv_axis_rotation_y: ""
e_adv_dark_scale: ""
e_adv_flat_scale: ""
#Optimization Settings
e_adv_lamino_group: False
e_adv_verbose: False
e_adv_slice_mem_coeff: 0.5
e_adv_num_gpu: ""
e_adv_slices_per_device: ""
...