# Default configuration file for ez_ufo_qt
# Modify at your own peril

---
e_indir: ""
e_tmpdir: ""
e_outdir: ""
e_darks: "darks"
e_flats: "flats"
e_tomo: "tomo"
e_flats2: "flats2"
e_bigtif: false
main_cor_axis_search_method: 1
main_cor_axis_search_interval: "1010,1030,0.5"
main_cor_search_row_start: 100
main_cor_recon_patch_size: 256
main_cor_axis_column: 0.0
main_cor_axis_increment_step: 0.0
main_filters_remove_spots: false
main_filters_remove_spots_threshold: 1000
main_filters_remove_spots_blur_sigma: 2
main_filters_ring_removal: false
main_filters_ring_removal_ufo_lpf: true
main_filters_ring_removal_ufo_lpf_1d_or_2d: true
main_filters_ring_removal_ufo_lpf_sigma_horizontal: 3
main_filters_ring_removal_ufo_lpf_sigma_vertical: 2
main_filters_ring_removal_sarepy_window_size: 21
main_filters_ring_removal_sarepy_wide: false
main_filters_ring_removal_sarepy_window: 91
main_filters_ring_removal_sarepy_SNR: 3
main_pr_phase_retrieval: false
main_pr_photon_energy: 20
main_pr_pixel_size: 3.6
main_pr_detector_distance: 0.1
main_pr_delta_beta_ratio: 200
main_region_select_rows: false
main_region_first_row: 100
main_region_number_rows: 200
main_region_nth_row: 20
main_region_clip_histogram: false
main_region_bit_depth: 8
main_region_histogram_min: 0.0
main_region_histogram_max: 0.0
e_pre: false
e_pre_cmd: "remove-outliers size=3 threshold=500 sign=1"
main_region_rotate_volume_clock: 0.0
main_region_crop_slices: false
main_region_crop_x: 0
e_dx: 0
main_region_crop_y: 0
main_region_crop_height: 0
e_dryrun: false
e_parfile: true
e_keep_tmp: false
e_sinFFC: false
e_sinFFC_method: 1
e_sinFFCEigenReps: 4
e_sinFFCEigenDowns: 2
e_sinFFCDowns: 4
e_openIV: True
e_common_darks_flats: False
e_common_darks: "Absolute path to darks"
e_common_flats: "Absolute path to flats"
e_use_common_flats2: False
e_common_flats2: "Absolute path to flats2"
#NLMDN Settings
e_nlmdn_apply_after_reco: False
e_nlmdn_indir: ""
e_nlmdn_input_is_file: False
e_nlmdn_outdir: ""
e_nlmdn_bigtif: False
e_nlmdn_r: 10
e_nlmdn_dx: 3
e_nlmdn_h: 0.0
e_nlmdn_sig: 0.0
e_nlmdn_w: 0.0
e_nlmdn_fast: True
e_nlmdn_autosig: False
e_nlmdn_dryrun: False
#ADVANCED TOFU Settings
e_adv_lamino_angle: 30
e_adv_overall_rotation: 360
e_adv_center_pos_z: ""
e_adv_axis_rotation_y: ""
e_adv_dark_scale: ""
e_adv_flat_scale: ""
#Optimization Settings
e_adv_lamino_group: False
e_adv_verbose: False
e_adv_slice_mem_coeff: 0.5
e_adv_num_gpu: ""
e_adv_slices_per_device: ""
...